spring:
  application:
    name: creator-settlement-api
  datasource:
    url: jdbc:h2:mem:settlement
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /api-docs
